version: '3.7'

services:
  mosquitto:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    volumes:
      - ./config:/mosquitto/config
      - ./config:/mosquitto/data
      - ./config:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
volumes:
  config:
  data:
  log: